### ISSUE TITLE
Configuration instruction: Quelpa

### ISSUE THREAD

**Issue by firmart** [lepisma/org-krita#5]
Until this package goes to Melpa, it would be nice to have a configuration snippet in the README to install automatically `org-krita`. [quelpa-use-package](https://github.com/quelpa/quelpa-use-package) can do it as follows:
```emacs-lisp
  (use-package org-krita
    :ensure t
    :quelpa (org-krita :fetcher github :repo "lepisma/org-krita" :files ("*.el" "resources"))
    :config
    (add-hook 'org-mode-hook 'org-krita-mode))  
```

**Comment by lepisma** [comment]
thanks, adding to the readme
